### ISSUE TITLE
Streaming mode

### ISSUE THREAD

**Issue by Mykotauro** [MrAyianaLex/streamdeck-steelseries-sonar#7] opened 2024-12-28 17:05 UTC
When i switch from Sonar to streaming mode, i cannot control streaming volumes and normal ones. If I return to classic mode all works fine.

Also chat Mix doesn't work (i have physical gameDAC)

- Plugin version: 1.4
- Sonar version: 77.0.0

**Comment by MrAyianaLex** [comment] 2024-12-28 17:09
I know, this is a way of working that I can't get around.
If you want to use the plugin, you have to do the updates only from the plugin.
You can see it the other way around, if you make changes from the plugin, they are not visible in the application, you have to close its window and reopen it to force an update

**Comment by MrAyianaLex** [comment] 2024-12-28 17:09
I know, this is a way of working that I can't get around.
If you want to use the plugin, you have to do the updates only from the plugin.
You can see it the other way around, if you make changes from the plugin, they are not visible in the application, you have to close its window and reopen it to force an update

**Closed as completed by MrAyianaLex** 2024-12-28 17:09 UTC

**Comment by Mykotauro** [comment] 2024-12-28 17:12
What do you mean with "update from the plugin?" When you download the latest version is not updated?

![image](https://github.com/user-attachments/assets/0ab45664-649f-4423-863d-fad639ff2731)

This is what I see

**Comment by MrAyianaLex** [comment] 2024-12-28 17:20
I haven't updated the plugin for a while, it works with the latest version of GG steelseries.
When I say update, I mean using buttons, like the one you mentioned.
If you want to change the mode (from classic to streamer, or vice versa, you have to do it from the plugin, not from the application).
The volume levels are independent between streamer and classic mode.
But if you change the mode from the GG application, the plugin does not have the information, and it tries to modify the sound of the old mode.
As for the volume between Chat and Games, if you have a device with its own control, you cannot switch to the other.
The plugin only "reproduces" the actions you would do in GG Steelseries, so it cannot switch to another.

**Comment by Mykotauro** [comment] 2024-12-28 17:29
I restarted the app and uninstalled the plugin.

I tried to switch with the plugin from classic to streaming mode but in GG application shows this error

![image](https://github.com/user-attachments/assets/7193a822-75b5-416e-95f1-cc10efddd39c)

**Comment by MrAyianaLex** [comment] 2024-12-28 17:33
This happens when Windows or GG SteelSeries does an update, you just have to put the values ​​back.
This problem is not related to the plugin.
For my part, I also have the problem with Discord which, with each update of GG SteelSeries, goes back to the wrong device.
But it's a problem with the application, not the plugin, I can't do anything.
When this happens, you also have to update the application buttons because the identifiers of the audio devices have been changed by GG SteelSeries

**Comment by Mykotauro** [comment] 2024-12-28 17:34
So have I to reinstall the application? How can I restore these values?

**Comment by MrAyianaLex** [comment] 2024-12-28 17:37
No need to reinstall, you just have to put the values ​​back from the application.
The easiest way is to put the audio devices you want to use back in GG SteelSeries, and then restart the application.
However, as explained, these problems are not related to the plugin, so this will be my last answer.

**Comment by Mykotauro** [comment] 2024-12-28 17:43
I tried your fix but nothing. Anyway I appreciate your help. Thx
